--- #YAML:1.0
name:               Apache-Session-LDAP
version:            0.2
abstract:           An implementation of Apache::Session
author:
    - Xavier Guimard <x.guimard@free.fr>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Apache::Session:  0
    Net::LDAP:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
